apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # ⚠️ 修改为你的 Prometheus 地址
    # 常见配置：
    # - Kubernetes 集群内: http://prometheus-server:9090
    # - Docker 本地: http://host.docker.internal:9090
    # - 远程地址: http://your-prometheus-ip:9090
    url: http://10.70.162.109:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
    editable: false
    
  # 如果使用 VictoriaMetrics，取消注释并配置
  # - name: VictoriaMetrics
  #   type: prometheus
  #   access: proxy
  #   url: http://victoriametrics:8428
  #   isDefault: false
  #   jsonData:
  #     httpMethod: POST
  #     timeInterval: "15s"
  #   editable: false
